name: Slither Analysis
on: [push]
permissions:
  # required for all workflows
  security-events: write

  # only required for workflows in private repositories
  actions: read
  contents: read
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crytic/slither-action@v0.1.1
        id: slither
        continue-on-error: true
        with:
          target: 'src/'
          sarif: results.sarif
          solc-version: '0.8.4'
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
